name: Build Docker Image

on:
  push:
    branches:
      - main


env:
  VER: 2.0.0-1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      
      -
        name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: | 
            ${{ secrets.DOCKERHUB_USERNAME }}/hpool-chia-miner:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/hpool-chia-miner:${{ env.VER }}